/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static com.google.common.truth.Truth.assertThat;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

public class AppTest {
    
    @Test
    @DisplayName("Greeting tests")
    void testAppHasAGreeting() {
        App app = new App();
        assertThat(app.getGreeting()).isNotNull();
        assertThat(app.getGreeting()).isEqualTo("Hello world with Gradle.");
        assertThat(app.getGreeting()).hasLength(24);
    }

    @Test
    @DisplayName("Math operations tests")
    void testNumbersOperations() {
        int precedence = 25 - 5 * 4 / 2 - 10 + 4;
        int precedenceOverriden = (((25 - 5) * 4) / (2 - 10)) + 4;
        String [] names = {"a",
            "b","c"};
        assertThat(precedence).isEqualTo(9);
        assertThat(precedenceOverriden).isEqualTo(-6);
    }
    
    @Test
    @DisplayName("String operation test")
    void testStringMethods() {
        String phoneNum = "404-543-2345";
        int index = phoneNum.indexOf("-");
        assertThat(index ).isEqualTo(3);
        
        int index2 = phoneNum.indexOf("-", index + 1);
        assertThat(index2 ).isEqualTo(7);
        
        
    }
    
    @Test
    @DisplayName("String sibtring test")
    void testStringSubtringMethod() {
        String phoneNum = "404-543-2345";
        
        assertThat(phoneNum.substring(3, 7) ).isEqualTo("-543");
        assertThat(phoneNum.substring(4, 7) ).isEqualTo("543");
        
        int index = phoneNum.indexOf("-");
        
        assertThat(phoneNum.substring(index+1, index+4) ).isEqualTo("-543");
        assertThat(phoneNum.substring(index+1, index+4) ).isEqualTo("543");
        
        assertThat(phoneNum.substring(7) ).isEqualTo("-2345");
        assertThat(phoneNum.substring(8) ).isEqualTo("2345");  
        
        int index2 = phoneNum.indexOf("-", index + 1);
        
        assertThat(phoneNum.substring(index2+1, index2+5) ).isEqualTo("-2345");
        assertThat(phoneNum.substring(index2+1, index2+5) ).isEqualTo("2345");
        
        StringBuilder certificatic = new StringBuilder("Certificatic");
        certificatic.append(" rules!");
        
        assertThat(certificatic.toString()).isEqualTo("Certificatic rules!");
    }
}
